FaceDetector:
  trained_model: /home/wht/face/code/Pytorch_Retinaface/weights/mobilenet0.25_Final.pth
  network: mobile0.25
  cpu: False
  confidence_threshold: 0.02
  top_k: 5000
  nms_threshold: 0.4
  keep_top_k: 750
  save_image: True
  vis_thres: 0.6